#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2016-05-13
# @Author  : Shoufu
# @Version : 2.7.6

import json

data_str = '''
{"base_resp":{"ret":0,"errmsg":"ok"},"comment":[],"elected_comment_total_cnt":0,"read_num":173,"like_num":3}
'''

data = json.loads(data_str)
print data
